
SELECT * FROM ALTERNATIVAS

SELECT * FROM ALUNOS

SELECT * FROM ALUNOS_EMPRESAS

SELECT * FROM ALUNOS_TREINAMENTOS

SELECT * FROM CADERNOS_RESPOSTAS

SELECT * FROM CERTIFICADOS

SELECT * FROM CONTEUDOS_PROGRAMATICOS

SELECT * FROM CURSOS

SELECT * FROM CURSOS_CONTEUDOS

SELECT * FROM CURSOS_QUESTOES

SELECT * FROM EMPRESAS

SELECT * FROM ENDERECOS_EMPRESAS

SELECT * FROM INSTRUTORES

SELECT * FROM INSTRUTORES_TREINAMENTOS

SELECT * FROM LISTAS_PRESENCAS

SELECT * FROM PESSOAS

SELECT * FROM PROVAS

SELECT * FROM PROVAS_QUESTOES

SELECT * FROM QUESTOES

SELECT * FROM TELEFONES_EMPRESAS

SELECT * FROM TELEFONES_PESSOAS

SELECT * FROM TREINAMENTOS

SELECT * FROM USUARIOS
